[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings=["@openzeppelin/contracts=node_modules/@openzeppelin/contracts"]

[rpc_endpoints]
anvil_local="${ANVIL_LOCAL_TESTNET}"
polygon_amoy = "${AMOY_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC}"
optimism_sepolia = "${OPTIMISM_SEPOLIA}"
eth_sepolia = "${ETHEREUM_SEPOLIA}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA}"

eth_mainnet = "${ETHEREUM_MAINNET}"
base_mainnet = "${BASE_MAINNET}"
polygon_mainnet = "${POLYGON_MAINNET}"
optimism_mainnet = "${OPTIMISM_MAINNET}"
arbitrum_mainnet = "${ARBITRUM_MAINNET}"


[etherscan]
polygon_amoy = { key = "${POLYGONSCAN_API}", url="https://api-amoy.polygonscan.com/api" }
base_sepolia = { key = "${BASESCAN_API}", url ="https://api-sepolia.basescan.org/api/"}
eth_sepolia = { key = "${ETHERSCAN_API_KEY}", url ="https://api-sepolia.etherscan.io/api"}
arbitrum_sepolia = { key = "${ARBISCAN_API}", url ="https://api-sepolia.arbiscan.io/api/"}

eth_mainnet = { key = "${ETHERSCAN_API_KEY}", url ="https://api.etherscan.io/api"}
base_mainnet = { key = "${BASESCAN_API}", url ="https://api.basescan.org/api/"}
polygon_mainnet = { key = "${POLYGONSCAN_API}", url ="https://api.polygonscan.com/api"}
arbitrum_mainnet = { key = "${ARBISCAN_API}", url ="https://api.arbiscan.io/api/"}
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options